### Get random screenshot (anonymous)

GET {{url}}/api/v1/screenshots/weighted
Accept-Language: {{locale}}
X-Timezone-Offset: {{utcOffset}}
X-Forwarded-For: {{ip}}

> {%
    client.global.set("screenshot", response.body);
%}

### Get random screenshot

GET {{url}}/api/v1/screenshots/weighted
Authorization: Creator name={{creatorName}}&id={{creatorId}}&provider=paradox&hwid={{hwid}}
Accept-Language: {{locale}}
X-Timezone-Offset: {{utcOffset}}
X-Forwarded-For: {{ip}}

> {%
    client.global.set("screenshot", response.body);
%}

### Get random screenshot weighted algorithms

GET {{url}}/api/v1/screenshots/weighted
    ?random=10
    &recent=10
    &archeologist=10
    &supporter=10
    &viewMaxAge=1
Authorization: Creator name={{creatorName}}&id={{creatorId}}&provider=paradox&hwid={{hwid}}
Accept-Language: {{locale}}
X-Timezone-Offset: {{utcOffset}}
X-Forwarded-For: {{ip}}

> {%
    client.global.set("screenshot", response.body);
%}

### Mark a screenshot as viewed

POST {{url}}/api/v1/screenshots/{{screenshot.id}}/views
Authorization: Creator name={{creatorName}}&id={{creatorId}}&provider=paradox&hwid={{hwid}}
Accept-Language: {{locale}}
X-Timezone-Offset: {{utcOffset}}
X-Forwarded-For: {{ip}}

### Report a screenshot

POST {{url}}/api/v1/screenshots/{{screenshot.id}}/reports
Authorization: Creator name={{creatorName}}&id={{creatorId}}&provider=paradox&hwid={{hwid}}
Accept-Language: {{locale}}
X-Timezone-Offset: {{utcOffset}}
X-Forwarded-For: {{ip}}

### Upload a screenshot

POST {{url}}/api/v1/screenshots
Authorization: Creator name={{creatorName}}&id={{creatorId}}&provider=paradox&hwid={{hwid}}
Accept-Language: {{locale}}
X-Timezone-Offset: {{utcOffset}}
Content-Type: multipart/form-data; boundary=WebAppBoundary
X-Forwarded-For: {{ip}}

--WebAppBoundary
Content-Disposition: form-data; name="cityName"

Colossal City

--WebAppBoundary
Content-Disposition: form-data; name="cityMilestone"

20

--WebAppBoundary
Content-Disposition: form-data; name="cityPopulation"

1200

--WebAppBoundary
Content-Disposition: form-data; name="screenshot"; filename="screenshot.jpg"

< screenshot.jpg
--WebAppBoundary--

> {%
    client.global.set("screenshot", response.body);
%}
