### List screenshots (anonymous)

GET {{url}}/api/v1/screenshots
Accept-Language: {{locale}}
X-Timezone-Offset: {{utcOffset}}
X-Forwarded-For: {{ip}}

### List my screenshots

GET {{url}}/api/v1/screenshots?creatorId=me
Authorization: Creator name={{creatorName}}&id={{creatorId}}&provider=paradox&hwid={{hwid}}
Accept-Language: {{locale}}
X-Timezone-Offset: {{utcOffset}}
X-Forwarded-For: {{ip}}

### Get a screenshot by ID

GET {{url}}/api/v1/screenshots/{{screenshot.id}}
Accept-Language: {{locale}}
X-Timezone-Offset: {{utcOffset}}
X-Forwarded-For: {{ip}}

> {%
  client.global.set("screenshot", response.body);
  client.global.set("creator", response.body.creator);
%}

### Get random screenshot (anonymous)

GET {{url}}/api/v1/screenshots/weighted
Accept-Language: {{locale}}
X-Timezone-Offset: {{utcOffset}}
X-Forwarded-For: {{ip}}

> {%
  client.global.set("screenshot", response.body);
  client.global.set("creator", response.body.creator);
%}

### Get random screenshot

GET {{url}}/api/v1/screenshots/weighted
Authorization: Creator name={{creatorName}}&id={{creatorId}}&provider=paradox&hwid={{hwid}}
Accept-Language: {{locale}}
X-Timezone-Offset: {{utcOffset}}
X-Forwarded-For: {{ip}}

> {%
  client.global.set("screenshot", response.body);
  client.global.set("creator", response.body.creator);
%}

### Get random screenshot weighted algorithms

GET {{url}}/api/v1/screenshots/weighted
  ?random=10
  &trending=10
  &recent=10
  &archeologist=10
  &supporter=10
  &viewMaxAge=1
Authorization: Creator name={{creatorName}}&id={{creatorId}}&provider=paradox&hwid={{hwid}}
Accept-Language: {{locale}}
X-Timezone-Offset: {{utcOffset}}
X-Forwarded-For: {{ip}}

> {%
  client.global.set("screenshot", response.body);
  client.global.set("creator", response.body.creator);
%}

### Delete a screenshot

DELETE {{url}}/api/v1/screenshots/{{screenshot.id}}
Authorization: Creator name={{creatorName}}&id={{creatorId}}&provider=paradox&hwid={{hwid}}
Accept-Language: {{locale}}
X-Timezone-Offset: {{utcOffset}}
X-Forwarded-For: {{ip}}

### Add a screenshot to favorites

POST {{url}}/api/v1/screenshots/{{screenshot.id}}/favorites
Authorization: Creator name={{creatorName}}&id={{creatorId}}&provider=paradox&hwid={{hwid}}
Accept-Language: {{locale}}
X-Timezone-Offset: {{utcOffset}}
X-Forwarded-For: {{ip}}

### Remove a screenshot from favorites

DELETE {{url}}/api/v1/screenshots/{{screenshot.id}}/favorites/mine
Authorization: Creator name={{creatorName}}&id={{creatorId}}&provider=paradox&hwid={{hwid}}
Accept-Language: {{locale}}
X-Timezone-Offset: {{utcOffset}}
X-Forwarded-For: {{ip}}

### Mark a screenshot as viewed

POST {{url}}/api/v1/screenshots/{{screenshot.id}}/views
Authorization: Creator name={{creatorName}}&id={{creatorId}}&provider=paradox&hwid={{hwid}}
Accept-Language: {{locale}}
X-Timezone-Offset: {{utcOffset}}
X-Forwarded-For: {{ip}}

### Report a screenshot

POST {{url}}/api/v1/screenshots/{{screenshot.id}}/reports
Authorization: Creator name={{creatorName}}&id={{creatorId}}&provider=paradox&hwid={{hwid}}
Accept-Language: {{locale}}
X-Timezone-Offset: {{utcOffset}}
X-Forwarded-For: {{ip}}

### Upload a screenshot

POST {{url}}/api/v1/screenshots
Authorization: Creator name={{creatorName}}&id={{creatorId}}&provider=paradox&hwid={{hwid}}
Accept-Language: {{locale}}
X-Timezone-Offset: {{utcOffset}}
Content-Type: multipart/form-data; boundary=WebAppBoundary
X-Forwarded-For: {{ip}}

--WebAppBoundary
Content-Disposition: form-data; name="cityName"

Colossal City

--WebAppBoundary
Content-Disposition: form-data; name="cityMilestone"

20

--WebAppBoundary
Content-Disposition: form-data; name="cityPopulation"

1200

--WebAppBoundary
Content-Disposition: form-data; name="modIds"

90641, 94394

--WebAppBoundary
Content-Disposition: form-data; name="renderSettings"

{ "aperture": 2.4 }

--WebAppBoundary
Content-Disposition: form-data; name="metadata"

{
  "platform": "WindowsPlayer",
  "gpuName": "JetBrains WebStorm HTTP Client",
  "gpuVendor": "JetBrains"
}

--WebAppBoundary
Content-Disposition: form-data; name="screenshot"; filename="screenshot.png"

< screenshot.png
--WebAppBoundary--

> {%
  client.global.set("screenshot", response.body);
%}
