### Get random screenshot

GET {{url}}/api/screenshot/weighted&incrementViews={{incrementViews}}

### Get random screenshot weighted algorithms

GET {{url}}/api/screenshot/weighted
    ?random=10
    &recent=10
    &lowViews=10
    &incrementViews={{incrementViews}}

### Upload a screenshot

POST {{url}}/api/screenshot/upload
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="creatorId"

a86bd575-6aba-4d83-abd5-756aba9d834a

--WebAppBoundary
Content-Disposition: form-data; name="creatorName"

toverux

--WebAppBoundary
Content-Disposition: form-data; name="cityName"

Colossal City

--WebAppBoundary
Content-Disposition: form-data; name="cityPopulation"

1200

--WebAppBoundary
Content-Disposition: form-data; name="screenshot"; filename="screenshot.jpg"

< screenshot.jpg
--WebAppBoundary--
