### Get random screenshot

GET {{url}}/api/screenshot/weighted?markViewed={{markViewed}}
Authorization: CreatorID {{creatorId}}
X-Forwarded-For: ::1

### Get random screenshot weighted algorithms

GET {{url}}/api/screenshot/weighted
    ?random=10
    &recent=10
    &archeologist=10
    &supporter=10
    &markViewed={{markViewed}}
    &viewMaxAge=1
Authorization: CreatorID {{creatorId}}
X-Forwarded-For: ::1

### Upload a screenshot

POST {{url}}/api/screenshot/upload
Authorization: CreatorID {{creatorId}}
Content-Type: multipart/form-data; boundary=WebAppBoundary
X-Forwarded-For: ::1

--WebAppBoundary
Content-Disposition: form-data; name="creatorName"

toverux

--WebAppBoundary
Content-Disposition: form-data; name="cityName"

Colossal City

--WebAppBoundary
Content-Disposition: form-data; name="cityMilestone"

20

--WebAppBoundary
Content-Disposition: form-data; name="cityPopulation"

1200

--WebAppBoundary
Content-Disposition: form-data; name="screenshot"; filename="screenshot.jpg"

< screenshot.jpg
--WebAppBoundary--
