import '@angular/compiler';
import { AngularAppEngine } from '@angular/ssr';
import { Logger } from '@nestjs/common';
import { config } from './config';

export {
  createWebRequestFromNodeRequest,
  writeResponseToNodeResponse
} from '@angular/ssr/node';

export let angularAppEngine: AngularAppEngine | undefined;

try {
  const { AngularAppEngine } = await import(
    // @ts-expect-error: generated by Angular
    '../../dist/server/server.mjs'
  );

  angularAppEngine = new AngularAppEngine();
} catch (error) {
  if (config.env == 'production') {
    throw error;
  }

  new Logger('Angular').error(
    `Failed to load Angular app engine manifest. Is the Angular app built?`,
    error
  );
}
